// ════════════════════════════════════════════════════════════════════════════
// Entitlement signing PUBLIC keys  —  Phase 2
//
// GENERATED by scripts/gen-entitlement-keypair.js. Do not hand-edit.
//
// These are PUBLIC keys. They are meant to ship inside app.asar; there is
// nothing here an attacker gains anything from. The matching private keys live
// in the control plane's secret store and must never appear in this repo.
//
// A MAP, not a single key, because entitlements are addressed by `kid`. An app
// build keeps verifying entitlements signed by any key it knows, so rotating
// the signing key does not strand machines running an older build. Drop a key
// from this map only when nothing in the field can still hold one it signed.
//
// ACTIVE_KID is what the control plane is expected to be signing with today.
// It is a hint for diagnostics only — verification always goes by the `kid` in
// the token header, never by this constant.
// ════════════════════════════════════════════════════════════════════════════

'use strict';

const KEYS = {
  "ent-20260819":
    "-----BEGIN PUBLIC KEY-----\n" +
    "MCowBQYDK2VwAyEAL7bcRL+Y/nTvmaCem/kd+sA0HTwkP+SYY2Pi1IzyFKk=\n" +
    "-----END PUBLIC KEY-----\n"
};

const ACTIVE_KID = "ent-20260819";

module.exports = { KEYS, ACTIVE_KID };
